import './globals.css'
import { Kanit } from 'next/font/google'
import { ReactNode } from 'react'

import { Album } from 'lucide-react'
import { SignIn } from '@/components/SignIn'
import { cookies } from 'next/headers'
import { UserData } from '@/components/UserData'
const kanit = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '500', '600', '700', '800'],
  variable: '--font-kanit',
})

export const metadata = {
  title: 'Simple Notes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const isAuthenticated = cookies().has('token')

  return (
    <html lang="pt-br">
      <body
        className={`${kanit.variable} flex min-h-screen flex-col bg-pgray-200 py-2 font-sans `}
      >
        <div className="flex flex-row items-center justify-between px-52 py-20 ">
          <div className="flex flex-col">
            <span className="text-6xl font-semibold">Simple Notes</span>
            {/* Divider */}
            <div className="my-5 h-0.5 w-full rounded-full bg-black" />
            {isAuthenticated ? <UserData /> : <SignIn />}
          </div>

          <Album
            size={128}
            color="white"
            className="rounded-full bg-black p-5"
          />
        </div>
        <div className="mx-40 flex min-h-screen flex-row rounded-lg border-4 border-black  bg-white">
          {/* Aside sectios - Note */}
          {children}
        </div>
      </body>
    </html>
  )
}
